/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_items__item_id__patch"];
        trace?: never;
    };
    "/api/outfits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outfits */
        get: operations["list_outfits_api_outfits_get"];
        put?: never;
        /** Create Outfit */
        post: operations["create_outfit_api_outfits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outfits/{outfit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show Outfit */
        get: operations["show_outfit_api_outfits__outfit_id__get"];
        put?: never;
        post?: never;
        /** Delete Outfit */
        delete: operations["delete_outfit_api_outfits__outfit_id__delete"];
        options?: never;
        head?: never;
        /** Update Outfit */
        patch: operations["update_outfit_api_outfits__outfit_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Category
         * @enum {string}
         */
        Category: "sports" | "casual" | "formal" | "outdoor";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            category: components["schemas"]["Category"];
            slot: components["schemas"]["Slot"];
            /** @default wanted */
            status: components["schemas"]["ItemStatus"];
        };
        /** ItemRead */
        ItemRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            category: components["schemas"]["Category"];
            slot: components["schemas"]["Slot"];
            status: components["schemas"]["ItemStatus"];
            /** Photo Public Id */
            photo_public_id: string | null;
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "owned" | "wanted";
        /** ItemUpdate */
        ItemUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            category?: components["schemas"]["Category"] | null;
            slot?: components["schemas"]["Slot"] | null;
            status?: components["schemas"]["ItemStatus"] | null;
        };
        /** OutfitCreate */
        OutfitCreate: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OutfitItemIn"][];
            /**
             * Name
             * @default Add a name to your outfit
             */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** OutfitItemIn */
        OutfitItemIn: {
            /** Item Id */
            item_id: number;
        };
        /** OutfitItemRead */
        OutfitItemRead: {
            slot: components["schemas"]["Slot"];
            /** Item Id */
            item_id: number;
            /** Name */
            name: string;
            /** Photo Public Id */
            photo_public_id: string | null;
        };
        /** OutfitRead */
        OutfitRead: {
            /** Items */
            items: components["schemas"]["OutfitItemRead"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["OutfitStatus"];
            /** Photo Public Id */
            photo_public_id: string | null;
        };
        /**
         * OutfitStatus
         * @enum {string}
         */
        OutfitStatus: "draft" | "created";
        /** OutfitUpdate */
        OutfitUpdate: {
            /** Items */
            items?: components["schemas"]["OutfitItemIn"][] | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["OutfitStatus"] | null;
        };
        /**
         * Slot
         * @enum {string}
         */
        Slot: "outer" | "top" | "bottom" | "footwear";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_items_api_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"][];
                };
            };
        };
    };
    create_item_api_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outfits_api_outfits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitRead"][];
                };
            };
        };
    };
    create_outfit_api_outfits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutfitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_outfit_api_outfits__outfit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outfit_api_outfits__outfit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_outfit_api_outfits__outfit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutfitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
